import { z } from 'zod';
import colors from './colors.json';
import dimensions from './dimensions.json';
import finishes from './finishes.json';
import lighting from './lighting.json';
import materials from './materials.json';
import radii from './radii.json';
import shadows from './shadows.json';
import spacing from './spacing.json';
import typography from './typography.json';
import { contrastRatio, isHexColor, resolveTokens, toCssDeclarations, type ResolvedToken } from './resolve';

export * from './resolve';

// ---------------------------------------------------------------------------
// Visual tokens (emitted as CSS custom properties)
// ---------------------------------------------------------------------------

/** Every visual token, flattened and alias-resolved. Planning dimensions are domain data and are excluded. */
export const designTokens: readonly ResolvedToken[] = resolveTokens(colors, typography, spacing, radii, shadows, {
  size: dimensions.size,
});

const tokenIndex = new Map(designTokens.map((token) => [token.path, token]));

export function hasToken(path: string): boolean {
  return tokenIndex.has(path);
}

export function getToken(path: string): ResolvedToken {
  const token = tokenIndex.get(path);
  if (!token) throw new Error(`Unknown design token "${path}".`);
  return token;
}

/** `cssVar('color.text.primary')` → `var(--cd-color-text-primary)`. Throws for unknown paths. */
export function cssVar(path: string): string {
  return `var(${getToken(path).cssVariable})`;
}

export function getTokensByPrefix(prefix: string): ResolvedToken[] {
  return designTokens.filter((token) => token.path === prefix || token.path.startsWith(`${prefix}.`));
}

/** Resolved hex value of a colour token. */
export function colorValue(path: string): string {
  const { value } = getToken(path);
  if (!isHexColor(value)) throw new Error(`Token "${path}" is not a hex colour.`);
  return value;
}

export const TOKEN_CSS_HEADER = '/* Generated by scripts/generate-token-css.ts from design-system/tokens/*.json — do not edit by hand. */';

/** The complete `tokens.css` stylesheet. */
export function buildTokenCss(): string {
  const lines = toCssDeclarations(designTokens).map(({ name, value }) => `  ${name}: ${value};`);
  return `${TOKEN_CSS_HEADER}\n:root {\n${lines.join('\n')}\n}\n`;
}

// ---------------------------------------------------------------------------
// Contrast requirements (WCAG 2.2 AA)
// ---------------------------------------------------------------------------

export interface ContrastRequirement {
  foreground: string;
  background: string;
  /** 4.5 for text, 3 for large text and non-text UI (borders, focus rings). */
  minimum: number;
  context: string;
}

const textOn = (foreground: string, backgrounds: string[], context: string): ContrastRequirement[] =>
  backgrounds.map((background) => ({ foreground, background, minimum: 4.5, context }));

const SURFACES = ['color.background.canvas', 'color.background.surface', 'color.background.subtle'];

export const CONTRAST_REQUIREMENTS: readonly ContrastRequirement[] = [
  ...textOn('color.text.primary', SURFACES, 'Primary text'),
  ...textOn('color.text.secondary', SURFACES, 'Secondary text'),
  ...textOn('color.text.muted', SURFACES, 'Muted text'),
  ...textOn('color.text.link', SURFACES, 'Links'),
  ...textOn('color.text.critical', SURFACES, 'Error messages'),
  ...textOn('color.text.inverse', ['color.background.inverse'], 'Inverse text'),
  ...textOn('color.text.primary', ['color.background.accent'], 'Text on accent panel'),
  ...textOn('color.action.primaryText', ['color.action.primary', 'color.action.primaryHover'], 'Primary button'),
  ...textOn('color.action.secondaryText', ['color.action.secondary', 'color.action.secondaryHover'], 'Secondary button'),
  ...textOn('color.action.dangerText', ['color.action.danger'], 'Danger button'),
  ...(['neutral', 'info', 'positive', 'caution', 'critical', 'pending'] as const).flatMap((tone) =>
    textOn(`color.status.${tone}.text`, [`color.status.${tone}.background`, 'color.background.surface'], `${tone} status`),
  ),
  { foreground: 'color.border.control', background: 'color.background.surface', minimum: 3, context: 'Form control boundary' },
  { foreground: 'color.border.focus', background: 'color.background.surface', minimum: 3, context: 'Focus ring on surface' },
  { foreground: 'color.border.focus', background: 'color.background.canvas', minimum: 3, context: 'Focus ring on canvas' },
];

export interface ContrastResult extends ContrastRequirement {
  ratio: number;
  passes: boolean;
}

export function checkContrast(requirement: ContrastRequirement): ContrastResult {
  const ratio = contrastRatio(colorValue(requirement.foreground), colorValue(requirement.background));
  return { ...requirement, ratio, passes: ratio >= requirement.minimum };
}

export function auditContrast(requirements: readonly ContrastRequirement[] = CONTRAST_REQUIREMENTS): ContrastResult[] {
  return requirements.map(checkContrast);
}

// ---------------------------------------------------------------------------
// Domain vocabularies (shared by tokens and schemas)
// ---------------------------------------------------------------------------

export const MATERIAL_CATEGORIES = [
  'natural-stone',
  'engineered-stone',
  'ceramic-tile',
  'vitrified-tile',
  'handmade-tile',
  'terrazzo',
  'cementitious-finish',
  'solid-wood',
  'veneer',
  'laminate',
  'paint',
  'plaster',
  'metal',
  'glass',
  'fabric',
  'wallpaper',
  'other',
] as const;
export type MaterialCategory = (typeof MATERIAL_CATEGORIES)[number];

export const FINISH_SHEENS = ['matt', 'low', 'satin', 'high', 'textured'] as const;
export const WET_FLOOR_GUIDANCE = ['avoid', 'verify', 'typically-suitable', 'not-applicable'] as const;
export type WetFloorGuidance = (typeof WET_FLOOR_GUIDANCE)[number];

export const LIGHTING_LAYERS = ['ambient', 'task', 'accent', 'decorative', 'night'] as const;
export type LightingLayer = (typeof LIGHTING_LAYERS)[number];

export const BATHROOM_ZONES = ['zone-0', 'zone-1', 'zone-2', 'outside-zones'] as const;
export type BathroomZone = (typeof BATHROOM_ZONES)[number];

/** IP code such as `IP44`, `IPX4` or `IP65`. First digit solids (0–6, X), second digit water (0–9, X). */
export const IP_RATING_PATTERN = /^IP[0-6X][0-9X]$/;

// ---------------------------------------------------------------------------
// Domain tokens (validated at import so malformed token files fail fast)
// ---------------------------------------------------------------------------

const text = z.string().trim().min(1);
const hexColor = z.string().regex(/^#[0-9A-Fa-f]{6}$/, 'Expected a 6-digit hex colour.');

const finishTokenSchema = z.object({
  label: text,
  appliesTo: z.array(z.enum(MATERIAL_CATEGORIES)).min(1),
  sheen: z.enum(FINISH_SHEENS),
  wetFloorGuidance: z.enum(WET_FLOOR_GUIDANCE),
  description: text,
  maintenance: text,
});
export type FinishToken = z.infer<typeof finishTokenSchema>;

const materialTokensSchema = z.object({
  categories: z.record(
    z.enum(MATERIAL_CATEGORIES),
    z.object({
      label: text,
      codePrefix: z.string().regex(/^[A-Z]{2}$/),
      considerations: z.array(text),
    }),
  ),
  references: z.array(
    z.object({
      id: text,
      label: text,
      category: z.enum(MATERIAL_CATEGORIES),
      origin: text,
      description: text,
      displayColor: hexColor,
      commonFinishes: z.array(text).min(1),
    }),
  ),
});
export type MaterialTokens = z.infer<typeof materialTokensSchema>;
export type MaterialReference = MaterialTokens['references'][number];

const lightingTokensSchema = z.object({
  colorTemperature: z.record(text, z.object({ kelvin: z.number().int().min(1800).max(6500), label: text, use: text })),
  colorRendering: z.record(text, z.object({ minimumCri: z.number().min(0).max(100), use: text })),
  illuminanceTargets: z.array(
    z
      .object({ id: text, label: text, minLux: z.number().positive(), maxLux: z.number().positive() })
      .refine((target) => target.minLux <= target.maxLux, 'minLux must not exceed maxLux'),
  ),
  layers: z.record(z.enum(LIGHTING_LAYERS), z.object({ label: text, description: text })),
  beamAngles: z.record(
    text,
    z
      .object({ label: text, minDeg: z.number().positive(), maxDeg: z.number().positive() })
      .refine((beam) => beam.minDeg < beam.maxDeg, 'minDeg must be below maxDeg'),
  ),
  bathroomZones: z.record(
    z.enum(BATHROOM_ZONES),
    z.object({ label: text, minimumIp: z.string().regex(IP_RATING_PATTERN).nullable(), description: text }),
  ),
});
export type LightingTokens = z.infer<typeof lightingTokensSchema>;

const clearanceSchema = z
  .object({ label: text, minimum: z.number().positive(), recommended: z.number().positive(), description: text })
  .refine((c) => c.minimum <= c.recommended, 'minimum must not exceed recommended');
const heightSchema = z
  .object({ label: text, typical: z.number().positive(), range: z.tuple([z.number().positive(), z.number().positive()]), description: text })
  .refine((h) => h.range[0] <= h.typical && h.typical <= h.range[1], 'typical must sit within range');

/**
 * Planning keys are declared here rather than inferred from the JSON so published type
 * declarations never reference the token files. The exhaustive enum records below make the
 * JSON and these lists fail fast if they drift apart.
 */
export const PLANNING_CLEARANCE_KEYS = [
  'wcFrontClear',
  'wcCentrelineToSide',
  'basinFrontClear',
  'showerAreaInternal',
  'bathroomDoorClearOpening',
  'circulationPath',
  'bedSideClear',
  'wardrobeFrontClear',
  'kitchenWorkAisle',
  'diningChairPullOut',
] as const;
export type PlanningClearanceKey = (typeof PLANNING_CLEARANCE_KEYS)[number];

export const PLANNING_HEIGHT_KEYS = ['kitchenCounter', 'vanityCounter', 'wcSeat', 'doorHead'] as const;
export type PlanningHeightKey = (typeof PLANNING_HEIGHT_KEYS)[number];

const planningGuidanceSchema = z.object({
  unit: z.literal('mm'),
  status: z.literal('guidance'),
  basis: text,
  clearances: z.record(z.enum(PLANNING_CLEARANCE_KEYS), clearanceSchema),
  heights: z.record(z.enum(PLANNING_HEIGHT_KEYS), heightSchema),
});

export type PlanningClearance = z.infer<typeof clearanceSchema>;
export type PlanningHeight = z.infer<typeof heightSchema>;
export type PlanningGuidance = z.infer<typeof planningGuidanceSchema>;

export const finishTokens: Readonly<Record<string, FinishToken>> = z
  .object({ finishes: z.record(text, finishTokenSchema) })
  .parse(finishes).finishes;

export const materialTokens: MaterialTokens = materialTokensSchema.parse(materials);

export const lightingTokens: LightingTokens = lightingTokensSchema.parse(lighting);

export const planningGuidance: PlanningGuidance = planningGuidanceSchema.parse(dimensions.planning);

export function getFinishToken(id: string): FinishToken | undefined {
  return finishTokens[id];
}

export function getMaterialReference(id: string): MaterialReference | undefined {
  return materialTokens.references.find((reference) => reference.id === id);
}
